/**
  * \file	main.c
  * \brief	Main program body
  */

/**
 * Copyleft (c) 2021 by Roland van Straten (rolandvs@github)
 *
 *	This program is a minimum concept of a bootloader.
 *	It checks on a certain location. If success it jumps over to it,
 *	otherwise it will flash a LED...
 *
 *	The project is located in the branch "leap" of the "skeleton_f091".
 *
 *
 */

#include <stdio.h>
#include "main.h"
#include "i2c.h"
#include "usart.h"
#include "gpio.h"

#include "bsp.h"	/* some support routines */


#define APPLICATION_ADDRESS (uint32_t)0x08004000


typedef  void (*pFunction)(void);


/* Jumping Jack Flash */
pFunction JumpToApplication;
uint32_t JumpAddress;


void SystemClock_Config(void);

/*****************
 * implementation
 *****************/

/**
  * \brief  The application entry point
  * \retval int
  */
int main(void)
{

  /* Reset of all peripherals, Initializes the Flash interface and the Systick */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* It seems that, at least when the HSE is used, the SysTick is not always enabled.
   * Calling HAL_Delay() will freeze the system.
   * - Flipping the above two calls "could" help. However, this is not as it is normally generated by STM32CubeMX.
   * - Adding the SysTick_Config() seems to solve the problem all or not together with changing the HSE_VALUE in stm32f0xx.c
   *   As a result the baudrate is not correct but half the actual speed
   *
   * - Adding the HSE_VALUE=16000000L value in this example in the project build (make) info seems to solves all the problems
   *   It looks like that the HSE_VALUE is checked in different parts of the HAL_F0xx libraries.
   *
   *   NEED TO CHECK THIS
   *
   *	HSI, HSE=16MHz, UART5, LED, HSE_MCO=8MHz, SYSCLK=48MHz, PLL, SysTick=1mS
   *
   */
#if(0)
  SysTick_Config(SystemCoreClock/1000); /* then it works */
#endif

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART2_UART_Init();
  MX_USART5_UART_Init();
  MX_I2C1_Init();

  bsp_led_off();		/* i will not tell you what happens here */
  bsp_console_init();	/* setup the use of the UART */

  printf("\r\nPOWERBOX Bootloader 0.1 [skeleton_f091][leap]\r\n");


  /* do not use the IAP services and execute the user program */

  /* test if user code is programmed starting from address "APPLICATION_ADDRESS" */

  if ( ((*(__IO uint32_t*)APPLICATION_ADDRESS) & 0x2FFE0000 ) == 0x20000000 )
  {
	  /* NOTE: if the IWDG is used and active it will never stop,
	   *       make sure to refresh the IWDG in the application program too!
	   */

	  /* show RUN .-. ..- -. */
		bsp_led_on(); bsp_delay_ms(100); bsp_led_off(); bsp_delay_ms(100);
		bsp_led_on(); bsp_delay_ms(300); bsp_led_off(); bsp_delay_ms(100);
		bsp_led_on(); bsp_delay_ms(100); bsp_led_off(); bsp_delay_ms(100);
		bsp_delay_ms(200);

		bsp_led_on(); bsp_delay_ms(100); bsp_led_off(); bsp_delay_ms(100);
		bsp_led_on(); bsp_delay_ms(100); bsp_led_off(); bsp_delay_ms(100);
		bsp_led_on(); bsp_delay_ms(300); bsp_led_off(); bsp_delay_ms(100);
		bsp_delay_ms(200);

		bsp_led_on(); bsp_delay_ms(300); bsp_led_off(); bsp_delay_ms(100);
		bsp_led_on(); bsp_delay_ms(100); bsp_led_off(); bsp_delay_ms(100);
		bsp_delay_ms(200);
	  /**/

	  /* initialize user application's Stack Pointer */
	  __set_MSP(*(__IO uint32_t*) APPLICATION_ADDRESS);
	  /* jump to user application */
	  JumpAddress = *(__IO uint32_t*) (APPLICATION_ADDRESS + 4);
	  JumpToApplication = (pFunction) JumpAddress;
	  JumpToApplication();
  }

  /* there is no user program, just stay here until hell freezes over or at least as long as the iwdg allows...*/

  while (1)
  {
	printf("No Application @ ADDR=0x08004000\r\n");
	bsp_led_on();
	bsp_delay_ms(10);
	bsp_led_off();
	bsp_delay_ms(10000);
  }

}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /* Enable HSE Oscillator and Activate PLL with HSE as source */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE|RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL6;
  RCC_OscInitStruct.PLL.PREDIV = RCC_PREDIV_DIV2;

  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /* Select PLL as system clock source and configure the HCLK, PCLK1 clocks dividers */
  RCC_ClkInitStruct.ClockType = (RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_PCLK1);
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
  PeriphClkInit.PeriphClockSelection = 	RCC_PERIPHCLK_USART2|RCC_PERIPHCLK_I2C1;
  PeriphClkInit.Usart2ClockSelection = RCC_USART2CLKSOURCE_PCLK1;
  PeriphClkInit.I2c1ClockSelection = RCC_I2C1CLKSOURCE_HSI;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }

  /* clock to the MCO output */
  HAL_RCC_MCOConfig(RCC_MCO, RCC_MCO1SOURCE_HSE, RCC_MCODIV_2);

}


/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
}
#endif /* USE_FULL_ASSERT */

